# Generated by Django 4.2.7 on 2025-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapinglog',
            name='url',
            field=models.URLField(blank=True, default='', help_text='URL that was scraped'),
        ),
        migrations.AddField(
            model_name='scrapinglog',
            name='user_agent_used',
            field=models.CharField(default='Mozilla/5.0 (compatible; PriceTrackerBot/1.0)', help_text='User agent string used for scraping', max_length=500),
        ),
    ]
